### PR TITLE
static page add

### PR DESCRIPTION
**Pull request by Paarmita**
index.html page added. It can be viewed at /static/index on the localhost.
screenshot from 2018-04-26 18-25-49
navigation.html page at /static/navigation
screenshot from 2018-04-26 13-55-43

### CODE REVIEW

**Comment by Paarmita** [comment]
@JessicaML

**Comment by JessicaML** [comment]
Paarmita, have a look at this branch and see how you get on with hosting the js files and css files. Let me know if you have more questions, otherwise i'll merge :) https://github.com/JessicaML/ScienceMotions-rails/tree/adding-homepage

**Comment by Paarmita** [comment]
@JessicaML Thanks for the reply, I understood the process. I will migrate all the pages from static site. You can merge this one. :)

**Comment by JessicaML** [comment]
Because there are conflicts in the Gemfile.lock - please add the Gemfile.lock from the master branch and then it is ok to merge

**Pull request merged**
